#!/bin/bash

ROOT=$(dirname "$0")
QEMU=$ROOT/qemu/x86_64-linux-user/qemu-x86_64
DFLAG=-singlestep 

if [[ ! -e "$QEMU" ]]; then
  echo "can't find qemu image (see $QEMU)"
  exit 1
fi

gdb $QEMU --args $QEMU $DFLAG "$@"
