/*
 * Minimal configuration for OpenSGX usage
 * Distinguishing features:
 *
 * See README.txt for usage instructions.
 */
#ifndef POLARSSL_CONFIG_H
#define POLARSSL_CONFIG_H

/* System support */
#define POLARSSL_HAVE_LONGLONG
#define POLARSSL_HAVE_ASM
//#define POLARSSL_NO_PLATFORM_ENTROPY

/* Networking support */
#define POLARSSL_HAVE_IPV6 /* Now mandatory for NET_C */
#define POLARSSL_NET_C

/* mbed TLS feature support */
#define POLARSSL_KEY_EXCHANGE_PSK_ENABLED
#define POLARSSL_SSL_PROTO_TLS1_2
#define POLARSSL_SSL_DISABLE_RENEGOTIATION

/* mbed TLS modules */
#define POLARSSL_AES_C
#define POLARSSL_CCM_C
#define POLARSSL_CIPHER_C
#define POLARSSL_CTR_DRBG_C
#define POLARSSL_ENTROPY_C
#define POLARSSL_MD_C
#define POLARSSL_SHA256_C
#define POLARSSL_SSL_CLI_C
#define POLARSSL_SSL_SRV_C
#define POLARSSL_SSL_TLS_C

/* Save RAM at the expense of ROM */
#define POLARSSL_AES_ROM_TABLES


#define POLARSSL_CIPHER_MODE_CBC
#define POLARSSL_CIPHER_MODE_CFB
#define POLARSSL_CIPHER_MODE_CTR
#define POLARSSL_CIPHER_PADDING_PKCS7
#define POLARSSL_CIPHER_PADDING_ONE_AND_ZEROS
#define POLARSSL_CIPHER_PADDING_ZEROS_AND_LEN
#define POLARSSL_CIPHER_PADDING_ZEROS
#define POLARSSL_KEY_EXCHANGE_PSK_ENABLED
#define POLARSSL_KEY_EXCHANGE_DHE_PSK_ENABLED
#define POLARSSL_KEY_EXCHANGE_RSA_PSK_ENABLED
#define POLARSSL_KEY_EXCHANGE_RSA_ENABLED
#define POLARSSL_KEY_EXCHANGE_DHE_RSA_ENABLED
#define POLARSSL_ERROR_STRERROR_DUMMY
#define POLARSSL_GENPRIME
#define POLARSSL_PKCS1_V15
#define POLARSSL_PKCS1_V21
#define POLARSSL_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO
#define POLARSSL_SSL_MAX_FRAGMENT_LENGTH
#define POLARSSL_SSL_PROTO_SSL3
#define POLARSSL_SSL_PROTO_TLS1
#define POLARSSL_SSL_PROTO_TLS1_1
#define POLARSSL_SSL_PROTO_TLS1_2
#define POLARSSL_X509_CHECK_KEY_USAGE
#define POLARSSL_X509_CHECK_EXTENDED_KEY_USAGE
#define POLARSSL_X509_RSASSA_PSS_SUPPORT
#define POLARSSL_AESNI_C
#define POLARSSL_AES_C
#define POLARSSL_ASN1_PARSE_C
#define POLARSSL_ASN1_WRITE_C
#define POLARSSL_BASE64_C
#define POLARSSL_BIGNUM_C
#define POLARSSL_CERTS_C
#define POLARSSL_CIPHER_C
#define POLARSSL_CTR_DRBG_C
#define POLARSSL_DES_C
#define POLARSSL_DHM_C
#define POLARSSL_ENTROPY_C
#define POLARSSL_ERROR_C
#define POLARSSL_GCM_C
#define POLARSSL_OID_C
#define POLARSSL_MD5_C
#define POLARSSL_PK_C
#define POLARSSL_PK_PARSE_C
#define POLARSSL_PK_WRITE_C
#define POLARSSL_PKCS5_C
#define POLARSSL_PKCS12_C
#define POLARSSL_PEM_PARSE_C
#define POLARSSL_PLATFORM_C
#define POLARSSL_RIPEMD160_C
#define POLARSSL_RSA_C
#define POLARSSL_SHA1_C
#define POLARSSL_SHA256_C
#define POLARSSL_SHA512_C
#define POLARSSL_SSL_CACHE_C
#define POLARSSL_SSL_CLI_C
#define POLARSSL_SSL_SRV_C
#define POLARSSL_SSL_TLS_C
#define POLARSSL_VERSION_C
#define POLARSSL_X509_USE_C
#define POLARSSL_X509_CRT_PARSE_C
#define POLARSSL_X509_CRL_PARSE_C
#define POLARSSL_X509_CSR_PARSE_C
#define POLARSSL_X509_CREATE_C
#define POLARSSL_X509_CRT_WRITE_C
#define POLARSSL_X509_CSR_WRITE_C

#include "polarssl/check_config.h"

#endif /* POLARSSL_CONFIG_H */
