#!/bin/bash

export ARFLAGS="rv"

./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --python=/usr/bin/python2 \
  --libexecdir=/usr/lib/qemu \
  --enable-debug \
  --enable-linux-aio \
  --localstatedir=/var \
  --target-list=x86_64-linux-user \
  #--enable-debug-info \
